version: '3.8'
services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alexsprynskyi/la-bs:django-travis
    container_name: django-travis
    networks: 
      - public
    ports: 
      - 80:8000
  monitor:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: alexsprynskyi/la-bs:django-travis
    container_name: django-travis
    networks: 
      - public

networks: 
  public:
    driver: bridge
